{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d681a749",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " FINAL INDUSTRY-LEVEL DATASET GENERATED\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "np.random.seed(42)\n",
    "\n",
    "rows = 5000\n",
    "dates = pd.date_range(start=\"2024-01-01\", end=\"2024-12-31\")\n",
    "\n",
    "df = pd.DataFrame({\n",
    "    \"Date\": np.random.choice(dates, rows),\n",
    "    \"Machine_ID\": np.random.choice([\"M1\", \"M2\", \"M3\", \"M4\"], rows),\n",
    "    \"Shift\": np.random.choice([\"A\", \"B\", \"C\"], rows),\n",
    "    \"Plant_Location\": np.random.choice([\"Mumbai\", \"Pune\", \"Chennai\"], rows)\n",
    "})\n",
    "\n",
    "# -----------------------------\n",
    "# Planned Production Time\n",
    "# -----------------------------\n",
    "df[\"Planned_Production_Time\"] = np.random.randint(420, 480, rows)\n",
    "\n",
    "# -----------------------------\n",
    "# Machine-specific behavior\n",
    "# -----------------------------\n",
    "downtime = []\n",
    "ideal_cycle = []\n",
    "defect_rate = []\n",
    "\n",
    "for machine in df[\"Machine_ID\"]:\n",
    "    \n",
    "    if machine == \"M1\":\n",
    "        # High downtime\n",
    "        downtime.append(np.random.randint(80, 140))\n",
    "        ideal_cycle.append(np.random.uniform(0.8, 1.0))\n",
    "        defect_rate.append(np.random.uniform(0.02, 0.04))\n",
    "        \n",
    "    elif machine == \"M2\":\n",
    "        # High defects\n",
    "        downtime.append(np.random.randint(30, 80))\n",
    "        ideal_cycle.append(np.random.uniform(0.8, 1.0))\n",
    "        defect_rate.append(np.random.uniform(0.08, 0.15))\n",
    "        \n",
    "    elif machine == \"M3\":\n",
    "        # Slow machine (low performance)\n",
    "        downtime.append(np.random.randint(30, 80))\n",
    "        ideal_cycle.append(np.random.uniform(1.2, 1.6))\n",
    "        defect_rate.append(np.random.uniform(0.02, 0.05))\n",
    "        \n",
    "    else:  # M4\n",
    "        # Best machine\n",
    "        downtime.append(np.random.randint(20, 60))\n",
    "        ideal_cycle.append(np.random.uniform(0.8, 1.0))\n",
    "        defect_rate.append(np.random.uniform(0.01, 0.03))\n",
    "\n",
    "df[\"Downtime\"] = downtime\n",
    "df[\"Ideal_Cycle_Time\"] = ideal_cycle\n",
    "\n",
    "# -----------------------------\n",
    "# Downtime Reason\n",
    "# -----------------------------\n",
    "df[\"Downtime_Reason\"] = np.random.choice(\n",
    "    [\"Breakdown\", \"Maintenance\", \"Setup\", \"Power Failure\"], rows\n",
    ")\n",
    "\n",
    "# Slightly increase breakdown impact\n",
    "for i, reason in enumerate(df[\"Downtime_Reason\"]):\n",
    "    if reason == \"Breakdown\":\n",
    "        df.loc[i, \"Downtime\"] *= 1.15\n",
    "\n",
    "# -----------------------------\n",
    "# Operating Time\n",
    "# -----------------------------\n",
    "df[\"Operating_Time\"] = df[\"Planned_Production_Time\"] - df[\"Downtime\"]\n",
    "\n",
    "# -----------------------------\n",
    "# Shift Impact (IMPORTANT )\n",
    "# -----------------------------\n",
    "shift_factor = []\n",
    "\n",
    "for shift in df[\"Shift\"]:\n",
    "    if shift == \"A\":\n",
    "        shift_factor.append(np.random.uniform(0.95, 1.0))  # best\n",
    "    elif shift == \"B\":\n",
    "        shift_factor.append(np.random.uniform(0.90, 0.95))\n",
    "    else:  # C\n",
    "        shift_factor.append(np.random.uniform(0.85, 0.90))  # worst\n",
    "\n",
    "shift_factor = np.array(shift_factor)\n",
    "\n",
    "# -----------------------------\n",
    "# Production Logic\n",
    "# -----------------------------\n",
    "efficiency = np.random.uniform(0.85, 0.98, rows) * shift_factor\n",
    "\n",
    "df[\"Total_Production\"] = (\n",
    "    df[\"Operating_Time\"] / df[\"Ideal_Cycle_Time\"]\n",
    ") * efficiency\n",
    "\n",
    "df[\"Total_Production\"] = df[\"Total_Production\"].astype(int)\n",
    "\n",
    "# -----------------------------\n",
    "# Defective Production\n",
    "# -----------------------------\n",
    "df[\"Defective_Production\"] = (\n",
    "    df[\"Total_Production\"] * defect_rate\n",
    ").astype(int)\n",
    "\n",
    "# -----------------------------\n",
    "# Derived Columns\n",
    "# -----------------------------\n",
    "df[\"Good_Production\"] = df[\"Total_Production\"] - df[\"Defective_Production\"]\n",
    "\n",
    "# -----------------------------\n",
    "# Missing Values (Realistic)\n",
    "# -----------------------------\n",
    "for col in [\"Downtime\", \"Ideal_Cycle_Time\", \"Defective_Production\"]:\n",
    "    df.loc[df.sample(frac=0.02).index, col] = np.nan\n",
    "\n",
    "# -----------------------------\n",
    "# Outliers (Controlled)\n",
    "# -----------------------------\n",
    "outlier_idx = df.sample(frac=0.01).index\n",
    "df.loc[outlier_idx, \"Downtime\"] *= 1.5\n",
    "\n",
    "# -----------------------------\n",
    "# Save Dataset\n",
    "# -----------------------------\n",
    "df.to_csv(\"../data/raw/manufacturing_data.csv\", index=False)\n",
    "\n",
    "print(\" FINAL INDUSTRY-LEVEL DATASET GENERATED\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a585f02a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
